#####################################
#                                   #
#  ||     ||  |||||||||  ||     ||  #
#  ||     ||  ||     ||  ||     ||  #
#  ||     ||  ||     ||  ||     ||  #
#  ||     ||  ||     ||  ||     ||  #
#  |||||||||  ||     ||  |||||||||  #
#  |||||||||  ||     ||  |||||||||  #
#  ||     ||  ||     ||  ||     ||  #
#  ||     ||  ||     ||  ||     ||  #
#  ||     ||  ||     ||  ||     ||  #
#  ||     ||  |||||||||  ||     ||  #
#                                   #
#####################################

# If you have any doubts regarding this please join my discord server for more questions
# https://discord.gg/c4vn5BPd
# OR
# Contact Latestion#0529

# --> Multi Language <-- #

# Language Support
# Currently Support Language:
#   - en = English
#   - pl = Polish
language: en

# --> General <-- #

Allow-Op: true # IF set to false, It wont allow any OPed player to Play the game!
WorldBorder: 200 # sets the world border from the location of the player who starts the game! DIAMETER !
Ban-Player-On-Death: true # Bans the player on death (if they don't have a beacon)
Make-Player-Spectator: true # Makes player spectator when they die without a beacon (Ban-Player-On-Death needs to be true)
Task-On-Player-Death: # runs the following command when a player dies when they don't have a beacon placed. (Ban-Player-On-Death & Make-Player-Spectator needs to be false)
  - "mv tp %player% world"
Allow-Spectators: true # Will allow any player to spectator, set to false and it will check if player has "hoh.spectate" permission
Inventory-Keep: 20 # Inventory keep chance! Compared out of 100. Keep 0 for disabling it!
Team-Damage: false # On or off team damage
Teleport-To-Spawn: false # Teleports All Player To Spawn When The Game Ends!
Disable-Other-Worlds: true # Disables END and NETHER, Set to false if you want to make HOH in other worlds too!
Cancel-Weather-Change: true # Disables weather change during game
Always-Day: true # Disable day changing
End-Game-If-Only-One-Beacon: false # Ends the game if only 1 beacon is left!
Allow-Other-Team-Beacon-Opening: true # Allows player to open beacons of other team

# --> Kit <-- #

# Normal kits
# Do not add beacon into it!
Kits:
  - STONE_PICKAXE, 1
  - STONE_PICKAXE, 1
  - STONE_AXE, 1
  - STONE_AXE, 1
  - STONE_SHOVEL, 1
  - STONE_SHOVEL, 1
  - COOKED_BEEF, 64

# Potions that will be given to the player!
# https://minecraftitemids.com/types/potion
# Use the above link to get the item id with ease and specify the number of items you would like to get!
# If you are using Essentials change use, "potion 1 {Potion:long_invisibility}"
Kits-Potion:
  - minecraft:potion{Potion:long_invisibility} 1 # 1 represents the number of potions

#Gives player item each time they respawn
# Personally 32 iron is best because, A full set of iron 24iron, set of tools 7 iron and a shield costs 32 iron!
Item-On-Respawn:
  - IRON_INGOT, 32
  - OAK_WOOD, 16
  - BREAD, 64

# --> Potion Effects <-- #

# Adds Certain Potion Effect On The Start of the game!
# SLOW_FALLING, 10, 1
# SLOW_FALLING --> Represent Which Type Of Effect
# 10 --> Represent Duration. In seconds
# 1 --> Represent strength of the potion effect
Enable-Effect-On-Start: true
Effect-On-Start:
  - SLOW_FALLING, 10, 1

# Adds Certain Potion Effect On The Start of the game!
# INVISIBILITY, 900, 5, 900
# INVISIBILITY --> Represents The Potion Type
# 900 --> Represent The Duration IN Seconds
# 5 --> Represents The Strength of the potion
# 900 --> Represents AFTER WHEN to apply that effect to the players in SECONDS!
Enable-Effect-After-Start: true
Effect-After-Start:
  - INVISIBILITY, 900, 5, 900

# --> Chat <-- #

# %message% = message
# %playername% = player name
# %playerteam% = player team name
Main-Chat-Format: "&f[&c%playerteam%&f] &f%playername% &7>> &f%message%"
Team-Chat-Format: "&f[&2TeamChat&f] &f%playername% &7>> &f%message%"

Rules-Messages: # /hoh rules (Sends all rules specified here)
  - "&4Rules"
  - "&2Your Rules"

# --> Supply Drops <-- #

# The plugin will pick any one combination of items between 1 and 2 from the above example. You can have unlimited amount of combinations!
# You can even use AIR to make the chest look better but thats all up to you.
# MAKE SURE ITS ONLY SKY THINGS
Auto-Supply-Drops: true
Supply-Drop-Delay: 10 # Delay between supply drops in minutes
World-Edit-Api: false # Allows World Edit api for better performance and more custom features
# MAKE SURE TO HAVE ALL YOUR SCHEMATICS IN YOUR WORLD EDIT FOLDER!
# Ignore the fellow if World-Edit-Api is on
Schem-Names:
  # - Drop_Ship_1
  # - Drop_Ship_2
Supply-Drop-Items:
  1:
    - BOW, 1
    - ARROW, 16
  2:
   - WHITE_WOOL, 1

# --> Episodes <-- #

Auto-Episodes: true # Enables Auto Episodes
Episode-Time: 30 # Grace period duration. In minutes!

# Sends Chat Reminder for episode endings
# 600, "&620 minutes remaining for episode %ep% end!"
# 600 --> Represents the duration this message runs after the episode ends
# Duration is also in seconds
# If you have any doubts regarding this please join my discord server for more questions
Episode-Reminders:
  1200: "&620 minutes remaining for episode %ep% end!"
  600: "&610 minutes remaining for episode %ep% end!"
  300: "&65 minutes remaining for episode %ep% end!"
  60: "&61 minutes remaining for episode %ep% end!"
  30: "&630 seconds remaining for episode %ep% end!"
  10: "&610 seconds remaining for episode %ep% end!"
  5: "&65 seconds remaining for episode %ep% end!"
  4: "&64 seconds remaining for episode %ep% end!"
  3: "&63 seconds remaining for episode %ep% end!"
  2: "&62 seconds remaining for episode %ep% end!"
  1: "&61 seconds remaining for episode %ep% end!"
  0: "&60 seconds remaining for episode %ep% end!"
  
Episode-End-Break-Time: 60 # Break time when a episode ends! In seconds. Set it to 0 to disable it
Disable-Beacon-Player-After-Episode-End: true

# --> Grace <-- #

Grace-Period: true # Enable / Disable Grace Period. Makes the 1st ep grace period
Grace-Period-Peaceful: true # Makes grace period truly peaceful
Grace-Duration: 30 # In Minutes
Disable-Beacon-Player-After-Grace: true

# --> Bungee Cord <-- #

Bungee-Cord: false #Enables Bungee Cord Support
Main-Lobby: "Main"
# <name>, <team size>, <total player>
# Eg: "hoh_1, 1, 2"
HOH-Servers:
  - "hoh_1, 1, 2"
  - "hoh_2, 2, 2"
# Make sure all your servers have restart script or this wont work!
# Console Command: /hoh queue <teamsize> <total players> <player name>
# Player Command: /hoh queue <teamsize> <total players>

# --> Team System <-- #

Replace-Custom-Team-Names: false # Replaces the team naming system to specified team names!
# Make Sure To Add More Names Soo You Don't Run Out Of Them :)
# COLOR CODES SUPPORTED
Team-Names:
  - "Red"
  - "Blue"
  - "Green"
  - "Yellow"
  - "Pink"
  - "Black"
  - "Green"
  - "White"
  - "Violet"
  - "Purple"
  - "Dark Blue"
  - "Dark Red"
  - "Dark Green"
  - "Dark Red"
  - "Dark Yellow"
  - "Brown"
  - "Cyan"

# Auto Joins Team For Solo When Game Is Started
# By Default Sets Replace-Custom-Team-Names to true
# GOOD FOR SERVERS WHO WANT TO MAKE THIS AS A MINI GAME
# **Recommended to use if your using BUNGEECORD**
Auto-Team-Join: false

# If player doesn't select a team in the given time, plugin force puts him in a team
# Gives the team Random name from Team-Names and Random teammate if not selected any!
# Set 0 to disable
# DOES NOT WORK IF Auto-Team-Join is enabled
Force-Team-After: 0 # In Seconds

# Removes player from game after player leaves the server (Before Game Start)
# Set 0 to disable
# DOES NOT WORK IF Auto-Team-Join is enabled
Remove-Player-After: 0 # In Seconds

# --> PARTY SYSTEM <-- #

#Only works with bungee cord

# Use party system provided by HideOrHunt For BungeeCord Servers
# Party Needs To Be The Perfect Size i.e. matching the max teamsize of the game!
# Commands:
# /hoh party invite <player> : Creates an party and invites the player to it
# /hoh party join <player> : Joins the party if he/she was invited!
# /hoh party leave : Removes the player from party, If the player is leader party is disbanded
# /hoh party disband: disbands the party
Party-System: false

# In Seconds, Disbands The Party If No One Joins
# Keep 0 to disable (Wont recommended)
Disband-Party-After: 20

# In seconds, Expiry time of a party invite
# Keep 0 to disable (Not recommended)
Party-Invite-Expire: 10

# --> Anti Xray <-- #

# Turns the beacon into AIR when there is no player near to it in a certain range
# Only works with Beacon and not with the chest or any other block near it!

# Its not perfect but it does its job
# Recommended to test it before you want to use it!

Anti-Xray: false
Show-Beacon-Range: 5 # Shows the beacon if there is a player in it x block range
Check-Delay: 1 # In seconds. Check if x seconds if player is in range. Recommended to keep on 1

# --> Legal Base <-- #

# Checks if player has valid base when they place the beacon!
Legal-Base-Detector: true # Enables or disables it
Time-To-Fix-Base: 120 # In Seconds. Allows player to fix his base within that time period
Remove-Beacon-If-Not-Fixed: false # Removes the beacon if they dont fix their base
Check-On-Beacon-Place: true # Checks if base is legal on beacon place

# Checks if player has valid base when grace ends!
# GRACE NEEDS TO BE ENABLED
Check-When-Grace-End: true

# Whitelists certain blocks inside the player base
# MAKE SURE NOT TO ADD ANY SOLID BLOCKS LIKE STONE, GRASS, DIRT ETC ETC
Whitelisted-Blocks:
  - sapling
  - leave
  - cobweb
  - flower
  - torch
  - bamboo
  - scaffolding
  - end_rod
  - fence
  - ladder
  - iron bar
  - chain
  - vines
  - carpet
  - sign
  - bed
  - lever
  - piston
  - pressure plate
  - trapdoor
  - redstone torch
  - tripwire
  - string
  - button
  - chest
  - restone_wire
  - comparator
  - repeater
  - door
  - rail
  - beacon
  - tall_grass
  - sugar_cane
  - kelp
  - seagrass
  - vines
  - slab
  - snow
  - water
  - lava


############################
# WORK IN PROGRESS##########
# DO NOT CHANGE THE VALUES##
############################


# --> Universal Beacon <-- #

# Universal Beacon turns your beacon to Furnace, Crafting Table, Enchanting Table, anvil and Storage Chest
# each of them get unlocked when you craft them in your beacon/craftingtable menu?
Universal-Beacon: true # Turn the beacon into a universal block

# --> Multiple Worlds <--#


# --> End <-- #