# If you have any doubts regarding this please join my discord server for more questions

language: en

# IF set to false, It wont allow any OPed player to Play the game!
Allow-Op: true

WorldBorder: 200 # sets the worldborder from the location of the player who starts the game! DIAMETER !

# Normal kits
# Do not add beacon into it!
Kits:
  - STONE_PICKAXE, 1
  - STONE_PICKAXE, 1
  - STONE_AXE, 1
  - STONE_AXE, 1
  - STONE_SHOVEL, 1
  - STONE_SHOVEL, 1
  - COOKED_BEEF, 64

# Potions that will be given to the player!
# https://minecraftitemids.com/types/potion
# Use the above link to get the item id with ease and sprecify the number of items you would like to get!
Kits-Potion:
  - minecraft:potion{Potion:long_invisibility} 1 # 1 represents the number of potions

# Adds Certain Potion Effect On The Start of the game!
# SLOW_FALLING, 10, 1
# SLOW_FALLING --> Represent Which Type Of Effect
# 10 --> Represent Duration. In seconds
# 1 --> Represent strength of the potion effect
Enable-Effect-On-Start: true
Effect-On-Start:
  - SLOW_FALLING, 10, 1

# Adds Certain Potion Effect On The Start of the game!
# INVISIBILITY, 900, 5, 900
# INVISIBILITY --> Represents The Potion Type
# 900 --> Represent The Duration IN Seconds
# 5 --> Represents The Strenght of the potion
# 900 --> Reprsents AFTER WHEN to apply that effect to the players in SECONDS!
Enable-Effect-After-Start: true
Effect-After-Start:
  - INVISIBILITY, 900, 5, 900

Ban-Player-On-Death: true # Bans the player on death

Inventory-Keep: 20 # Inventory keep chance! Compared out of 100. Keep 0 for disabling it!

#Gives player item each time they respawn
# Personally 32 iron is best because, A full set of iron 24iron, set of tooks 7 iron and a shield costs 32 iron!
Item-On-Respawn:
  - IRON_INGOT, 32
  - OAK_WOOD, 16

# The plugin will pick any one combination of items between 1 and 2 from the above example. You can have unlimited amount of combinations!
# You can even use AIR to make the chest look better but thats all up to you.
Auto-Supply-Drops: true
Supply-Drop-Delay: 10 # Delay between supply drops in minutes
Supply-Drop-Items:
  1:
    - BOW, 1
    - ARROW, 16
  2:
   - WHITE_WOOL, 1

# Enables Auto Episodes
Auto-Episodes: true
Grace-Period: true # Enable / Disable Grace Period. Makes the 1st ep grace period
Grace-Period-Peaceful: true # Makes grace period truly peaceful
Episode-Time: 20 # Grace period duration. In minutes!

# Sends Chat Reminder for episode endings
# 600, "&620 minutes remaining for episode %ep% end!"
# 600 --> Represents the duration this message runs after the episode ends
# Duration is also in seconds
# If you have any doubts regarding this please join my discord server for more questions
Episode-Reminders:
  1200: "&620 minutes remaining for episode %ep% end!"
  600: "&610 minutes remaining for episode %ep% end!"
  300: "&65 minutes remaining for episode %ep% end!"
  60: "&61 minutes remaining for episode %ep% end!"
  30: "&630 seconds remaining for episode %ep% end!"
  10: "&610 seconds remaining for episode %ep% end!"
  5: "&65 seconds remaining for episode %ep% end!"
  4: "&64 seconds remaining for episode %ep% end!"
  3: "&63 seconds remaining for episode %ep% end!"
  2: "&62 seconds remaining for episode %ep% end!"
  1: "&61 seconds remaining for episode %ep% end!"
  0: "&60 seconds remaining for episode %ep% end!"
  
Episode-End-Break-Time: 60 # Break time when a episode ends! In seconds. Set it to 0 to disable it

Team-Damage: false # On or off team damage 

Rules-Messages:
  - "&4Rules"
  - "&2Your Rules"
  
# %message%
# %playername%
# %playerteam%
Main-Chat-Format: "&f[&c%playerteam%&f] &f%playername% &7>> &f%message%"
Team-Chat-Format: "&f[&2TeamChat&f] &f%playername% &7>> &f%message%"
